name: Run benchmarks

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write
  issues: write
  contents: write
  pull-requests: write

jobs:
  build:
    strategy:
      matrix:
        os: ["macos-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: npm ci && npm run bench
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "./results"
          default_author: github_actions
          message: "Update benchmark results"
