on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: "git clone https://github.com/fabian-hiller/valibot.git valibotdir"
      - run: "ls -lh valibotdir"
